### ISSUE TITLE
Improve flash messages

### ISSUE THREAD

**Issue by Ptrboro** [Tomaszabc/Plants#1]
Flash messages are rather ugly now and they break the layout:
![Screenshot 2024-08-11 at 11 11 17](https://github.com/user-attachments/assets/2ebbd645-7e36-487f-b754-e0cfa8740220)

Let's use https://www.stimulus-components.com/docs/stimulus-notification to improve them.

**Comment by Tomaszabc** [comment]
I created 1-improve-flash-messages branch, merged main to it and added it to Your Issue. There can be no differences between main and new branch. Can You accept it this way?

![obraz](https://github.com/user-attachments/assets/5160e09a-ce17-4f0d-8405-a614f1f2483a)
