### ISSUE TITLE
Empty state for index of plants

### ISSUE THREAD

**Issue by Ptrboro** [Tomaszabc/Plants#2]
Let's display an empty state when a user has not added plants yet.

So instead of this:

![Screenshot 2024-08-11 at 11 12 42](https://github.com/user-attachments/assets/af5fe63b-b984-493d-aeaf-a58ef0695aa2)

We want something like this:

![Screenshot 2024-08-11 at 11 18 15 (1)](https://github.com/user-attachments/assets/788846dd-4557-4596-a400-6b8468f5d466)

you can use this image if you want:
![empty pots](https://github.com/user-attachments/assets/450acac5-1a7a-4268-8f3e-7a6fc1b54535)

**Comment by Tomaszabc** [comment]
![obraz](https://github.com/user-attachments/assets/4d03cf45-5096-4ccb-bcf2-77820c1f8150)

Done.
