### ISSUE TITLE
Display last watering time in a human friendly format

### ISSUE THREAD

**Issue by Ptrboro** [Tomaszabc/Plants#3]
Instead of "Podlano <date time>" we should display something like ""Watered 2 days ago", "Watered 5 hours ago" etc.
![Screenshot 2024-08-11 at 11 32 42](https://github.com/user-attachments/assets/1e904c72-3149-4663-96a8-7864e9e827c9)

I think this helper function can be used: https://api.rubyonrails.org/v7.1.3.4/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words

**Comment by Tomaszabc** [comment]
![obraz](https://github.com/user-attachments/assets/005c0fed-98a5-434b-bb62-96195cab4e60)
