### ISSUE TITLE
Allow users to delete watering logs

### ISSUE THREAD

**Issue by Ptrboro** [Tomaszabc/Plants#4]
We should allow users to delete the watering logs they added. This will be useful e.g. when someone added it by mistake.

Let's add "X" icon next to the watering logs. When clicked user should be prompted to confirm the deletion.
![Screenshot 2024-08-11 at 11 40 51](https://github.com/user-attachments/assets/45e5786d-1539-4a8e-bda3-d2d6d8c7a428)

**Comment by Tomaszabc** [comment]
![obraz](https://github.com/user-attachments/assets/2c929970-1369-42c2-8d55-cf4c79a2ae3f)
